### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by vladdoster** [singularityhub/containers#16]
I know there is at least one place where I was was attempting to hover over it and see what it was but nothing popped up. This can be a huge issue for screen readers and would be nice to have since it can be useful to figure out what a button does if not super clear given the UI.

I'm creating this issue to:

1. Gather examples
2. See if it can be fixed through jekyll or how much work might be required
3. Break into more issues if need be and work through them.

**Comment by vladdoster** [comment]
Whoops, wrong repo!

**Comment by vladdoster** [comment]
Well, actually, I might as well comb through this repo as well to avoid a context switch.

**Comment by vsoch** [comment]
Would you like me to transfer the issue to sregistry?

**Comment by vladdoster** [comment]
No thank you, I think this repo is more approachable to start off with to get familiar with what all accessibility might entail.
